TARGET = balance

SOURCES = main.c conf/buffer.c conf/confparser.c conf/confxml.c util/biquad.c util/realtimedata.c modifiers/torquetilt.c modifiers/turntilt.c modifiers/speedtilt.c modifiers/basictilt.c modifiers/untilt.c

VESC_C_LIB_PATH=../../c_libs/
include $(VESC_C_LIB_PATH)rules.mk

